server:
  port: 9999


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sharding_jdbc
#    password: 123456
#    username: root
#    driver-class-name: com.mysql.jdbc.Driver


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sharding_jdbc
    password: 123456
    username: root
    driver-class-name: org.postgresql.Driver